# Generated by Django 4.2.6 on 2023-11-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_goods_main_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.goods')),
            ],
        ),
        migrations.CreateModel(
            name='HugeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.goods')),
            ],
        ),
    ]
