# Generated by Django 4.2.6 on 2023-12-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_goods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='articul',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
