# Generated by Django 4.2.6 on 2023-12-17 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_brands_brands_pic_category_cat_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='MainBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.brands')),
            ],
        ),
    ]
