# Generated by Django 4.2.6 on 2023-10-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_buyer_category_colors_goods_sizes_sizestogoodtable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='main_pic',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
