# Generated by Django 4.2.6 on 2023-12-23 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_maincats_mainbrands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item_name',
        ),
        migrations.AlterField(
            model_name='goods',
            name='brand_id',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='MainApp.brands'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
