# Generated by Django 4.2.6 on 2024-01-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_alter_goods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price_with_sale',
            field=models.IntegerField(blank=True, default=5000),
            preserve_default=False,
        ),
    ]
